## Numpy -> Numeric Python

In last session we talked about list in Python. We can use list in various condition but when we want to deal with numeric values, it is better to use Numpy array.

In [1]:
l = [1, 2, 3, 4, 5]
l

[1, 2, 3, 4, 5]

Numpy is one of the useful Python libraries that we use it when we want to work with numeric values. Before Use any library in Python, We must import that library

In [2]:
import numpy as np

### Numpy array

In [3]:
na = np.array(l)
print(na)
print(type(na))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [6]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.full((4,4), 11)

array([[11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

With linspace method, You can divide the range of numbers into n equal parts:
for example below I divide numbers between 0 and 10 into 5 parts.

In [11]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Random

return a random number between 0 and 1

In [12]:
np.random.rand()

0.4112747503266111

return a random number in normal distirbution:

Normal Distribution:
<br>mean = 0
<br>std = 1



In [13]:
np.random.randn()

-1.029821064791579

In [15]:
np.random.randint(1000)

733

In [16]:
np.random.randint(100, 200, 10)

array([109, 189, 175, 192, 186, 177, 192, 141, 171, 172])

### Array Attributes & Methods

In [20]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a.shape

(9,)

In [22]:
a = a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
a.shape

(3, 3)

max number in a

In [24]:
np.max(a)

8

max number in each row of a

In [25]:
np.max(a, axis=1)

array([2, 5, 8])

max number in each column

In [26]:
np.max(a, axis=0)

array([6, 7, 8])

In [27]:
b = np.array([1, 20, 5, 7, 3, 4, 2])
b

array([ 1, 20,  5,  7,  3,  4,  2])

index of greatest value in array

In [28]:
np.argmax(b)

1

index of lowest value in array

In [29]:
np.argmin(b)

0

In [30]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[19, 18, 17],
              [16, 15, 14],
              [13, 12, 11]])

In [31]:
print(a.shape)
print(b.shape)

(3, 3)
(3, 3)


concat two array in vertical mode

In [33]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [19, 18, 17],
       [16, 15, 14],
       [13, 12, 11]])

concat two array in horizontal mode

In [34]:
np.hstack((a,b))

array([[ 1,  2,  3, 19, 18, 17],
       [ 4,  5,  6, 16, 15, 14],
       [ 7,  8,  9, 13, 12, 11]])

Also We can use concatenate method

In [35]:
np.concatenate((a,b), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [19, 18, 17],
       [16, 15, 14],
       [13, 12, 11]])

In [36]:
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3, 19, 18, 17],
       [ 4,  5,  6, 16, 15, 14],
       [ 7,  8,  9, 13, 12, 11]])

### Operations on Arrays

In [37]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
b

array([[19, 18, 17],
       [16, 15, 14],
       [13, 12, 11]])

In [39]:
a + b

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [40]:
a - b

array([[-18, -16, -14],
       [-12, -10,  -8],
       [ -6,  -4,  -2]])

In [41]:
a * b

array([[19, 36, 51],
       [64, 75, 84],
       [91, 96, 99]])

In [42]:
a / b

array([[0.05263158, 0.11111111, 0.17647059],
       [0.25      , 0.33333333, 0.42857143],
       [0.53846154, 0.66666667, 0.81818182]])

In [43]:
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [44]:
a // 5

array([[0, 0, 0],
       [0, 1, 1],
       [1, 1, 1]])

### Indexing & Slicing

#### 1D

In [46]:
c = np.arange(10, 20)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
c[1]

11

In [48]:
c[:5]

array([10, 11, 12, 13, 14])

In [49]:
c[5:]

array([15, 16, 17, 18, 19])

In [50]:
c[:6:2]

array([10, 12, 14])

In [51]:
c[:-4]

array([10, 11, 12, 13, 14, 15])

In [52]:
c[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#### 2D

In [56]:
d = np.arange(20).reshape(4,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
d[1]

array([5, 6, 7, 8, 9])

In [58]:
d[1][1]

6

In [60]:
d[:,1]

array([ 1,  6, 11, 16])

In [61]:
d[:2,:2]

array([[0, 1],
       [5, 6]])

In [62]:
d[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

### Other Method

In [63]:
np.mean(d)

9.5

mean in each row

In [64]:
np.mean(d, axis=1)

array([ 2.,  7., 12., 17.])

mean in each column

In [65]:
np.mean(d, axis=0)

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [66]:
np.std(d)

5.766281297335398

sum of each row

In [67]:
np.sum(d, axis=1)

array([10, 35, 60, 85])

sum of each column

In [68]:
np.sum(d, axis=0)

array([30, 34, 38, 42, 46])

In [69]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
b

array([[19, 18, 17],
       [16, 15, 14],
       [13, 12, 11]])

### Linear Algebra

matrix multiplication

In [71]:
np.matmul(a,b)

array([[ 90,  84,  78],
       [234, 219, 204],
       [378, 354, 330]])

In [73]:
np.linalg.det(a)

0.0

In [77]:
e = np.array([[2, 5, 7],
              [11, 10, 11],
              [8, 9, 12]])
e

array([[ 2,  5,  7],
       [11, 10, 11],
       [ 8,  9, 12]])

In [78]:
np.linalg.det(e)

-45.000000000000036

In [79]:
np.linalg.inv(e)

array([[-0.46666667, -0.06666667,  0.33333333],
       [ 0.97777778,  0.71111111, -1.22222222],
       [-0.42222222, -0.48888889,  0.77777778]])