In [42]:
pip install numpy
pip install pandas

SyntaxError: ignored

In [11]:
import numpy as np

In [12]:
a = np.array([1,2,3])
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print (a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [15]:
b = np.array([[1,2,3], [4,5,6]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [16]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [17]:
a = np.ones((1,2))
print(a)

[[1. 1.]]


In [18]:
a = np.full((2,2), 7)
print(a)

[[7 7]
 [7 7]]


In [19]:
a = np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [22]:
import random as rand
b = np.random.random((2,2))
print(b)

[[0.61574276 0.16843882]
 [0.46475463 0.21358099]]


In [24]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [27]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_1 = b[1, :]
print(row_1, row_1.shape)

[5 6 7 8] (4,)


In [29]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_1 = b[1:2, :]
print(row_1, row_1.shape)

[[5 6 7 8]] (1, 4)


In [30]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
bool_idx = (b>2)
print(bool_idx)

[[False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [32]:
a = np.array([1,2])
b = np.array([1.0, 2,0])
c = np.array([1,2], dtype = np.int64)
print(a.dtype, b.dtype, c.dtype)

int64 float64 int64


In [34]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
print(x + y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [35]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
print(x - y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [36]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
print(x * y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [37]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
print(x / y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [39]:
x = np.array([[1,2], [3,4]])
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [40]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
print(np.dot(x,y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [43]:
import pandas as pd

In [45]:
mydataset = {
    'cars': ["BMW", "Volvo", "Ford"],
    'passings': [3, 7, 2]
}
x = pd.DataFrame(mydataset)
print(x)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [46]:
print(pd.__version__)

1.5.3


In [47]:
a = [1, 7 ,2]
x = pd.Series(a)
print(x)

0    1
1    7
2    2
dtype: int64


In [51]:
a = [1, 7 ,2]
b = pd.Series(a, index = ["x", "y", "z"])
print(b)
print(b["x"])

x    1
y    7
z    2
dtype: int64
1


In [52]:
calories = {"day1": 420, "day2": 380, "day3": 390}
a = pd.Series(calories)
print(a)

day1    420
day2    380
day3    390
dtype: int64


In [53]:
calories = {"day1": 420, "day2": 380, "day3": 390}
a = pd.Series(calories, index = ["day1", "day2"])
print(a)

day1    420
day2    380
dtype: int64


In [54]:
x = {"calories": [420, 380,390],
            "duration": [50,40,45]
            }
a = pd.DataFrame(x)
print(a)

   calories  duration
0       420        50
1       380        40
2       390        45
